apiVersion: v1
kind: Pod
metadata:
  name: cpu-stress
spec:
  containers:
  - name: cpu-stress
    image: ${AZ_ACR_NAME}.azurecr.io/stress:v1 # IMPORTANT: update with your own repository
    imagePullPolicy: Always
    env:
    - name: timeout
      value: "5m"
  restartPolicy: Never
